
import 'package:intl_phone_field/countries.dart';

List<Country> _mojeZemlje= [
    Country(
    name: "Croatia",
    nameTranslations: {
      "sk": "Chorvátsko",
      "se": "Kroátia",
      "pl": "Chorwacja",
      "no": "Kroatia",
      "ja": "クロアチア",
      "it": "Croazia",
      "zh": "克罗地亚",
      "nl": "Kroatië",
      "de": "Kroatien",
      "fr": "Croatie",
      "es": "Croacia",
      "en": "Croatia",
      "pt_BR": "Croácia",
      "sr-Cyrl": "Хрватска",
      "sr-Latn": "Hrvatska",
      "zh_TW": "克羅埃西亞",
      "tr": "Hırvatistan",
      "ro": "Croația",
      "ar": "كرواتيا",
      "fa": "کرواسی",
      "yue": "克羅地亞"
    },
    flag: "🇭🇷",
    code: "HR",
    dialCode: "385",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: "Albania",
    nameTranslations: {
      "sk": "Albánsko",
      "se": "Albánia",
      "pl": "Albania",
      "no": "Albania",
      "ja": "アルバニア",
      "it": "Albania",
      "zh": "阿尔巴尼亚",
      "nl": "Albanië",
      "de": "Albanien",
      "fr": "Albanie",
      "es": "Albania",
      "en": "Albania",
      "pt_BR": "Albânia",
      "sr-Cyrl": "Албанија",
      "sr-Latn": "Albanija",
      "zh_TW": "阿爾巴尼亞",
      "tr": "Arnavutluk",
      "ro": "Albania",
      "ar": "ألبانيا",
      "fa": "آلبانی",
      "yue": "阿爾巴尼亞"
    },
    flag: "🇦🇱",
    code: "AL",
    dialCode: "355",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Austria",
    nameTranslations: {
      "sk": "Rakúsko",
      "se": "Nuortariika",
      "pl": "Austria",
      "no": "Østerrike",
      "ja": "オーストリア",
      "it": "Austria",
      "zh": "奥地利",
      "nl": "Oostenrijk",
      "de": "Österreich",
      "fr": "Autriche",
      "es": "Austria",
      "en": "Austria",
      "pt_BR": "Áustria",
      "sr-Cyrl": "Аустрија",
      "sr-Latn": "Austrija",
      "zh_TW": "奥地利",
      "tr": "Avusturya",
      "ro": "Austria",
      "ar": "النمسا",
      "fa": "اتریش",
      "yue": "奧地利"
    },
    flag: "🇦🇹",
    code: "AT",
    dialCode: "43",
    minLength: 13,
    maxLength: 13,
  ),
  Country(
    name: "Belarus",
    nameTranslations: {
      "sk": "Bielorusko",
      "se": "Vilges-Ruošša",
      "pl": "Białoruś",
      "no": "Hviterussland",
      "ja": "ベラルーシ",
      "it": "Bielorussia",
      "zh": "白俄罗斯",
      "nl": "Belarus",
      "de": "Belarus",
      "fr": "Biélorussie",
      "es": "Bielorrusia",
      "en": "Belarus",
      "pt_BR": "Bielo-Rússia",
      "sr-Cyrl": "Белорусија",
      "sr-Latn": "Belorusija",
      "zh_TW": "白俄羅斯",
      "tr": "Belarus",
      "ro": "Belarus",
      "ar": "بيلاروس",
      "fa": "بلاروس",
      "yue": "白俄羅斯"
    },
    flag: "🇧🇾",
    code: "BY",
    dialCode: "375",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Belgium",
    nameTranslations: {
      "sk": "Belgicko",
      "se": "Belgia",
      "pl": "Belgia",
      "no": "Belgia",
      "ja": "ベルギー",
      "it": "Belgio",
      "zh": "比利时",
      "nl": "België",
      "de": "Belgien",
      "fr": "Belgique",
      "es": "Bélgica",
      "en": "Belgium",
      "pt_BR": "Bélgica",
      "sr-Cyrl": "Белгија",
      "sr-Latn": "Belgija",
      "zh_TW": "比利時",
      "tr": "Belçika",
      "ro": "Belgia",
      "ar": "بلجيكا",
      "fa": "بلژیک",
      "yue": "比利時"
    },
    flag: "🇧🇪",
    code: "BE",
    dialCode: "32",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Bosnia and Herzegovina",
    nameTranslations: {
      "sk": "Bosna a Hercegovina",
      "se": "Bosnia-Hercegovina",
      "pl": "Bośnia i Hercegowina",
      "no": "Bosnia-Hercegovina",
      "ja": "ボスニア・ヘルツェゴビナ",
      "it": "Bosnia ed Erzegovina",
      "zh": "波斯尼亚和黑塞哥维那",
      "nl": "Bosnië en Herzegovina",
      "de": "Bosnien und Herzegowina",
      "fr": "Bosnie-Herzégovine",
      "es": "Bosnia y Herzegovina",
      "en": "Bosnia & Herzegovina",
      "pt_BR": "Bósnia e Herzegovina",
      "sr-Cyrl": "Босна и Херцеговина",
      "sr-Latn": "Bosna i Hercegovina",
      "zh_TW": "波士尼亞和黑塞哥維那",
      "tr": "Bosna Hersek",
      "ro": "Bosnia și Herțegovina",
      "ar": "البوسنة والهرسك",
      "fa": "بوسنی و هرزگوین",
      "yue": "波斯尼亞黑塞哥維那"
    },
    flag: "🇧🇦",
    code: "BA",
    dialCode: "387",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Bulgaria",
    nameTranslations: {
      "sk": "Bulharsko",
      "se": "Bulgária",
      "pl": "Bułgaria",
      "no": "Bulgaria",
      "ja": "ブルガリア",
      "it": "Bulgaria",
      "zh": "保加利亚",
      "nl": "Bulgarije",
      "de": "Bulgarien",
      "fr": "Bulgarie",
      "es": "Bulgaria",
      "en": "Bulgaria",
      "pt_BR": "Bulgária",
      "sr-Cyrl": "Бугарска",
      "sr-Latn": "Bugarska",
      "zh_TW": "保加利亞",
      "tr": "Bulgaristan",
      "ro": "Bulgaria",
      "ar": "بلغاريا",
      "fa": "بلغارستان",
      "yue": "保加利亞"
    },
    flag: "🇧🇬",
    code: "BG",
    dialCode: "359",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Cyprus",
    nameTranslations: {
      "sk": "Cyprus",
      "se": "Kypros",
      "pl": "Cypr",
      "no": "Kypros",
      "ja": "キプロス",
      "it": "Cipro",
      "zh": "塞浦路斯",
      "nl": "Cyprus",
      "de": "Zypern",
      "fr": "Chypre",
      "es": "Chipre",
      "en": "Cyprus",
      "pt_BR": "Chipre",
      "sr-Cyrl": "Кипар",
      "sr-Latn": "Kipar",
      "zh_TW": "塞普勒斯",
      "tr": "Kıbrıs",
      "ro": "Cipru",
      "ar": "قبرص",
      "fa": "قبرس",
      "yue": "塞浦路斯"
    },
    flag: "🇨🇾",
    code: "CY",
    dialCode: "357",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Czech Republic",
    nameTranslations: {
      "sk": "Česko",
      "se": "Čeahkka",
      "pl": "Czechy",
      "no": "Tsjekkia",
      "ja": "チェコ",
      "it": "Cechia",
      "zh": "捷克",
      "nl": "Tsjechië",
      "de": "Tschechien",
      "fr": "Tchéquie",
      "es": "Chequia",
      "en": "Czechia",
      "pt_BR": "Czechia",
      "sr-Cyrl": "Чешка",
      "sr-Latn": "Češka",
      "zh_TW": "捷克",
      "tr": "Çek Cumhuriyeti",
      "ro": "Cehia",
      "ar": "جمهورية التشيك",
      "fa": "جمهوری چک",
      "yue": "捷克共和國"
    },
    flag: "🇨🇿",
    code: "CZ",
    dialCode: "420",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Denmark",
    nameTranslations: {
      "sk": "Dánsko",
      "se": "Dánmárku",
      "pl": "Dania",
      "no": "Danmark",
      "ja": "デンマーク",
      "it": "Danimarca",
      "zh": "丹麦",
      "nl": "Denemarken",
      "de": "Dänemark",
      "fr": "Danemark",
      "es": "Dinamarca",
      "en": "Denmark",
      "pt_BR": "Dinamarca",
      "sr-Cyrl": "Данска",
      "sr-Latn": "Danska",
      "zh_TW": "丹麥",
      "tr": "Danimarka",
      "ro": "Danemarca",
      "ar": "الدنمارك",
      "fa": "دانمارک",
      "yue": "丹麥"
    },
    flag: "🇩🇰",
    code: "DK",
    dialCode: "45",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Finland",
    nameTranslations: {
      "sk": "Fínsko",
      "se": "Suopma",
      "pl": "Finlandia",
      "no": "Finland",
      "ja": "フィンランド",
      "it": "Finlandia",
      "zh": "芬兰",
      "nl": "Finland",
      "de": "Finnland",
      "fr": "Finlande",
      "es": "Finlandia",
      "en": "Finland",
      "pt_BR": "Finlândia",
      "sr-Cyrl": "Финска",
      "sr-Latn": "Finska",
      "zh_TW": "芬蘭",
      "tr": "Finlandiya",
      "ro": "Finlanda",
      "ar": "فنلندا",
      "fa": "فنلاند",
      "yue": "芬蘭"
    },
    flag: "🇫🇮",
    code: "FI",
    dialCode: "358",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: "France",
    nameTranslations: {
      "sk": "Francúzsko",
      "se": "Frankriika",
      "pl": "Francja",
      "no": "Frankrike",
      "ja": "フランス",
      "it": "Francia",
      "zh": "法国",
      "nl": "Frankrijk",
      "de": "Frankreich",
      "fr": "France",
      "es": "Francia",
      "en": "France",
      "pt_BR": "França",
      "sr-Cyrl": "Француска",
      "sr-Latn": "Francuska",
      "zh_TW": "法國",
      "tr": "Fransa",
      "ro": "Franța",
      "ar": "فرنسا",
      "fa": "فرانسه",
      "yue": "法國"
    },
    flag: "🇫🇷",
    code: "FR",
    dialCode: "33",
    minLength: 9,
    maxLength: 9,
  ),
   Country(
    name: "Germany",
    nameTranslations: {
      "sk": "Nemecko",
      "se": "Duiska",
      "pl": "Niemcy",
      "no": "Tyskland",
      "ja": "ドイツ",
      "it": "Germania",
      "zh": "德国",
      "nl": "Duitsland",
      "de": "Deutschland",
      "fr": "Allemagne",
      "es": "Alemania",
      "en": "Germany",
      "pt_BR": "Alemanha",
      "sr-Cyrl": "Немачка",
      "sr-Latn": "Nemačka",
      "zh_TW": "德國",
      "tr": "Almanya",
      "ro": "Germania",
      "ar": "ألمانيا",
      "fa": "آلمان",
      "yue": "德國"
    },
    flag: "🇩🇪",
    code: "DE",
    dialCode: "49",
    minLength: 9,
    maxLength: 13,
  ),
  Country(
    name: "Greece",
    nameTranslations: {
      "sk": "Grécko",
      "se": "Greika",
      "pl": "Grecja",
      "no": "Hellas",
      "ja": "ギリシャ",
      "it": "Grecia",
      "zh": "希腊",
      "nl": "Griekenland",
      "de": "Griechenland",
      "fr": "Grèce",
      "es": "Grecia",
      "en": "Greece",
      "pt_BR": "Grécia",
      "sr-Cyrl": "Грчка",
      "sr-Latn": "Grčka",
      "zh_TW": "希臘",
      "tr": "Yunanistan",
      "ro": "Grecia",
      "ar": "اليونان",
      "fa": "یونان",
      "yue": "希臘"
    },
    flag: "🇬🇷",
    code: "GR",
    dialCode: "30",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: "Hungary",
    nameTranslations: {
      "sk": "Maďarsko",
      "se": "Ungár",
      "pl": "Węgry",
      "no": "Ungarn",
      "ja": "ハンガリー",
      "it": "Ungheria",
      "zh": "匈牙利",
      "nl": "Hongarije",
      "de": "Ungarn",
      "fr": "Hongrie",
      "es": "Hungría",
      "en": "Hungary",
      "pt_BR": "Hungria",
      "sr-Cyrl": "Мађарска",
      "sr-Latn": "Mađarska",
      "zh_TW": "匈牙利",
      "tr": "Macaristan",
      "ro": "Ungaria",
      "ar": "المجر",
      "fa": "مجارستان",
      "yue": "匈牙利"
    },
    flag: "🇭🇺",
    code: "HU",
    dialCode: "36",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Iceland",
    nameTranslations: {
      "sk": "Island",
      "se": "Islánda",
      "pl": "Islandia",
      "no": "Island",
      "ja": "アイスランド",
      "it": "Islanda",
      "zh": "冰岛",
      "nl": "IJsland",
      "de": "Island",
      "fr": "Islande",
      "es": "Islandia",
      "en": "Iceland",
      "pt_BR": "Islândia",
      "sr-Cyrl": "Исланд",
      "sr-Latn": "Island",
      "zh_TW": "冰島",
      "tr": "İzlanda",
      "ro": "Islanda",
      "ar": "آيسلندا",
      "fa": "ایسلند",
      "yue": "冰島"
    },
    flag: "🇮🇸",
    code: "IS",
    dialCode: "354",
    minLength: 7,
    maxLength: 9,
  ),
  Country(
    name: "Ireland",
    nameTranslations: {
      "sk": "Írsko",
      "se": "Irlánda",
      "pl": "Irlandia",
      "no": "Irland",
      "ja": "アイルランド",
      "it": "Irlanda",
      "zh": "爱尔兰",
      "nl": "Ierland",
      "de": "Irland",
      "fr": "Irlande",
      "es": "Irlanda",
      "en": "Ireland",
      "pt_BR": "Irlanda",
      "sr-Cyrl": "Ирска",
      "sr-Latn": "Irska",
      "zh_TW": "愛爾蘭",
      "tr": "İrlanda",
      "ro": "Irlanda",
      "ar": "أيرلندا",
      "fa": "ایرلند",
      "yue": "愛爾蘭"
    },
    flag: "🇮🇪",
    code: "IE",
    dialCode: "353",
    minLength: 7,
    maxLength: 9,
  ),
  Country(
    name: "Liechtenstein",
    nameTranslations: {
      "sk": "Lichtenštajnsko",
      "se": "Liechtenstein",
      "pl": "Liechtenstein",
      "no": "Liechtenstein",
      "ja": "リヒテンシュタイン",
      "it": "Liechtenstein",
      "zh": "列支敦士登",
      "nl": "Liechtenstein",
      "de": "Liechtenstein",
      "fr": "Liechtenstein",
      "es": "Liechtenstein",
      "en": "Liechtenstein",
      "pt_BR": "Liechtenstein",
      "sr-Cyrl": "Лихтенштајн",
      "sr-Latn": "Lihtenštajn",
      "zh_TW": "列支敦斯登",
      "tr": "Lihtenştayn",
      "ro": "Liechtenstein",
      "ar": "ليختنشتاين",
      "fa": "لیختن‌اشتاین",
      "yue": "列支敦士登"
    },
    flag: "🇱🇮",
    code: "LI",
    dialCode: "423",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Luxembourg",
    nameTranslations: {
      "sk": "Luxembursko",
      "se": "Luxembourg",
      "pl": "Luksemburg",
      "no": "Luxemburg",
      "ja": "ルクセンブルク",
      "it": "Lussemburgo",
      "zh": "卢森堡",
      "nl": "Luxemburg",
      "de": "Luxemburg",
      "fr": "Luxembourg",
      "es": "Luxemburgo",
      "en": "Luxembourg",
      "pt_BR": "Luxemburgo",
      "sr-Cyrl": "Луксенбург",
      "sr-Latn": "Luksenburg",
      "zh_TW": "盧森堡",
      "tr": "Lüksemburg",
      "ro": "Luxemburg",
      "ar": "لوكسمبورغ",
      "fa": "لوکزامبورگ",
      "yue": "盧森堡"
    },
    flag: "🇱🇺",
    code: "LU",
    dialCode: "352",
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    name: "Macedonia",
    nameTranslations: {
      "sk": "Severné Macedónsko",
      "se": "North Macedonia",
      "pl": "Macedonia Północna",
      "no": "Nord-Makedonia",
      "ja": "北マケドニア",
      "it": "Macedonia del Nord",
      "zh": "北马其顿",
      "nl": "Noord-Macedonië",
      "de": "Nordmazedonien",
      "fr": "Macédoine du Nord",
      "es": "Macedonia del Norte",
      "en": "North Macedonia",
      "pt_BR": "Macedônia do Norte",
      "sr-Cyrl": "Северна Македонија",
      "sr-Latn": "Severna Makedonija",
      "zh_TW": "北馬其頓",
      "tr": "Kuzey Makedonya",
      "ro": "Macedonia de Nord",
      "ar": "مقدونيا",
      "fa": "مقدونیه",
      "yue": "馬其頓（前南斯拉夫共和國）"
    },
    flag: "🇲🇰",
    code: "MK",
    dialCode: "389",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Netherlands",
    nameTranslations: {
      "sk": "Holandsko",
      "se": "Vuolleeatnamat",
      "pl": "Holandia",
      "no": "Nederland",
      "ja": "オランダ",
      "it": "Paesi Bassi",
      "zh": "荷兰",
      "nl": "Nederland",
      "de": "Niederlande",
      "fr": "Pays-Bas",
      "es": "Países Bajos",
      "en": "Netherlands",
      "pt_BR": "Países Baixos",
      "sr-Cyrl": "Холандија",
      "sr-Latn": "Holandija",
      "zh_TW": "荷蘭",
      "tr": "Hollanda",
      "ro": "Olanda",
      "ar": "هولندا",
      "fa": "هلند",
      "yue": "荷蘭"
    },
    flag: "🇳🇱",
    code: "NL",
    dialCode: "31",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Poland",
    nameTranslations: {
      "sk": "Poľsko",
      "se": "Polen",
      "pl": "Polska",
      "no": "Polen",
      "ja": "ポーランド",
      "it": "Polonia",
      "zh": "波兰",
      "nl": "Polen",
      "de": "Polen",
      "fr": "Pologne",
      "es": "Polonia",
      "en": "Poland",
      "pt_BR": "Polônia",
      "sr-Cyrl": "Пољска",
      "sr-Latn": "Poljska",
      "zh_TW": "波蘭",
      "tr": "Polonya",
      "ro": "Polonia",
      "ar": "بولندا",
      "fa": "لهستان",
      "yue": "波蘭"
    },
    flag: "🇵🇱",
    code: "PL",
    dialCode: "48",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Romania",
    nameTranslations: {
      "sk": "Rumunsko",
      "se": "Románia",
      "pl": "Rumunia",
      "no": "Romania",
      "ja": "ルーマニア",
      "it": "Romania",
      "zh": "罗马尼亚",
      "nl": "Roemenië",
      "de": "Rumänien",
      "fr": "Roumanie",
      "es": "Rumanía",
      "en": "Romania",
      "pt_BR": "Romênia",
      "sr-Cyrl": "Румунија",
      "sr-Latn": "Rumunija",
      "zh_TW": "羅馬尼亞",
      "tr": "Romanya",
      "ro": "România",
      "ar": "رومانيا",
      "fa": "رومانی",
      "yue": "羅馬尼亞"
    },
    flag: "🇷🇴",
    code: "RO",
    dialCode: "40",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Serbia",
    nameTranslations: {
      "sk": "Srbsko",
      "se": "Serbia",
      "pl": "Serbia",
      "no": "Serbia",
      "ja": "セルビア",
      "it": "Serbia",
      "zh": "塞尔维亚",
      "nl": "Servië",
      "de": "Serbien",
      "fr": "Serbie",
      "es": "Serbia",
      "en": "Serbia",
      "pt_BR": "Sérvia",
      "sr-Cyrl": "Србија",
      "sr-Latn": "Srbija",
      "zh_TW": "塞爾維亞",
      "tr": "Sırbistan",
      "ro": "Serbia",
      "ar": "صربيا",
      "fa": "صربستان",
      "yue": "塞爾維亞"
    },
    flag: "🇷🇸",
    code: "RS",
    dialCode: "381",
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    name: "Slovakia",
    nameTranslations: {
      "sk": "Slovensko",
      "se": "Slovákia",
      "pl": "Słowacja",
      "no": "Slovakia",
      "ja": "スロバキア",
      "it": "Slovacchia",
      "zh": "斯洛伐克",
      "nl": "Slowakije",
      "de": "Slowakei",
      "fr": "Slovaquie",
      "es": "Eslovaquia",
      "en": "Slovakia",
      "pt_BR": "Eslováquia",
      "sr-Cyrl": "Словачка",
      "sr-Latn": "Slovačka",
      "zh_TW": "斯洛伐克",
      "tr": "Slovakya",
      "ro": "Slovacia",
      "ar": "سلوفاكيا",
      "fa": "اسلواکی",
      "yue": "斯洛伐克"
    },
    flag: "🇸🇰",
    code: "SK",
    dialCode: "421",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Slovenia",
    nameTranslations: {
      "sk": "Slovinsko",
      "se": "Slovenia",
      "pl": "Słowenia",
      "no": "Slovenia",
      "ja": "スロベニア",
      "it": "Slovenia",
      "zh": "斯洛文尼亚",
      "nl": "Slovenië",
      "de": "Slowenien",
      "fr": "Slovénie",
      "es": "Eslovenia",
      "en": "Slovenia",
      "pt_BR": "Eslovênia",
      "sr-Cyrl": "Словеније",
      "sr-Latn": "Slovenija",
      "zh_TW": "斯洛維尼亞",
      "tr": "Slovenya",
      "ro": "Slovenia",
      "ar": "سلوفينيا",
      "fa": "اسلوونی",
      "yue": "斯洛文尼亞"
    },
    flag: "🇸🇮",
    code: "SI",
    dialCode: "386",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: "Spain",
    nameTranslations: {
      "sk": "Španielsko",
      "se": "Spánia",
      "pl": "Hiszpania",
      "no": "Spania",
      "ja": "スペイン",
      "it": "Spagna",
      "zh": "西班牙",
      "nl": "Spanje",
      "de": "Spanien",
      "fr": "Espagne",
      "es": "España",
      "en": "Spain",
      "pt_BR": "Espanha",
      "sr-Cyrl": "Шпанија",
      "sr-Latn": "Španija",
      "zh_TW": "西班牙",
      "tr": "İspanya",
      "ro": "Spania",
      "ar": "إسبانيا",
      "fa": "اسپانیا",
      "yue": "西班牙"
    },
    flag: "🇪🇸",
    code: "ES",
    dialCode: "34",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: "Sweden",
    nameTranslations: {
      "sk": "Švédsko",
      "se": "Ruoŧŧa",
      "pl": "Szwecja",
      "no": "Sverige",
      "ja": "スウェーデン",
      "it": "Svezia",
      "zh": "瑞典",
      "nl": "Zweden",
      "de": "Schweden",
      "fr": "Suède",
      "es": "Suecia",
      "en": "Sweden",
      "pt_BR": "Suécia",
      "sr-Cyrl": "Шведска",
      "sr-Latn": "Švedska",
      "zh_TW": "瑞典",
      "tr": "İsveç",
      "ro": "Suedia",
      "ar": "السويد",
      "fa": "سوئد",
      "yue": "瑞典"
    },
    flag: "🇸🇪",
    code: "SE",
    dialCode: "46",
    minLength: 7,
    maxLength: 13,
  ),
  Country(
    name: "Switzerland",
    nameTranslations: {
      "sk": "Švajčiarsko",
      "se": "Šveica",
      "pl": "Szwajcaria",
      "no": "Sveits",
      "ja": "スイス",
      "it": "Svizzera",
      "zh": "瑞士",
      "nl": "Zwitserland",
      "de": "Schweiz",
      "fr": "Suisse",
      "es": "Suiza",
      "en": "Switzerland",
      "pt_BR": "Suíça",
      "sr-Cyrl": "Швајцарска",
      "sr-Latn": "Švajcarska",
      "zh_TW": "瑞士",
      "tr": "İsviçre",
      "ro": "Elveţia",
      "ar": "سويسرا",
      "fa": "سوئیس",
      "yue": "瑞士"
    },
    flag: "🇨🇭",
    code: "CH",
    dialCode: "41",
    minLength: 9,
    maxLength: 12,
  ),
  Country(
    name: "Ukraine",
    nameTranslations: {
      "sk": "Ukrajina",
      "se": "Ukraina",
      "pl": "Ukraina",
      "no": "Ukraina",
      "ja": "ウクライナ",
      "it": "Ucraina",
      "zh": "乌克兰",
      "nl": "Oekraïne",
      "de": "Ukraine",
      "fr": "Ukraine",
      "es": "Ucrania",
      "en": "Ukraine",
      "pt_BR": "Ucrânia",
      "sr-Cyrl": "Украјина",
      "sr-Latn": "Ukrajina",
      "zh_TW": "烏克蘭",
      "tr": "Ukrayna",
      "ro": "Ucraína",
      "ar": "أوكرانيا",
      "fa": "اوکراین",
      "yue": "烏克蘭"
    },
    flag: "🇺🇦",
    code: "UA",
    dialCode: "380",
    minLength: 9,
    maxLength: 9,
  ),
];